### PR TITLE
fix: fix marker's setters and getters to use element properties

### LINKED ISSUE #41: Markers: setters/getters for draggable, caption, iconUrl, position properties don't work
When trying to set this properties to a marker by using setter methods defined in GoogleMapMarkers class, client side values are not updated so nothing happens.

Setters and getters should set/get the element properties as in [GoogleMapPolygon ](https://github.com/FlowingCode/GoogleMapsAddon/blob/be1e078e1a37561900c1a404654dc4580e1b178b/src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPolygon.java#L62) class.

### PR DESCRIPTION
**Pull request by paodb**
Close #41

### CODE REVIEW

File: src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java [hunk 1]
```diff
@@ -83,11 +83,10 @@ public GoogleMapMarker(String caption, LatLon position, boolean draggable, Strin
   }
 
   private void initialize() {
-    this.getElement().setAttribute("title", caption);
-    this.getElement().setAttribute("latitude", "" + position.getLat());
-    this.getElement().setAttribute("longitude", "" + position.getLon());
-    this.getElement().setAttribute("draggable", String.valueOf(draggable));
-    this.getElement().setAttribute("icon", iconUrl);
+    this.setCaption(caption);
```
Comment (javier-godoy) [inline src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java:86]: Now that the getters/setters work directly on the element properties, the only purpose of the private members is passing the constructor parameters to `initialize()`. Please refactor `initialize` with the only constructor that calls it.

**Review by javier-godoy — CHANGES_REQUESTED** [review]

File: src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java (hunk 1 above)
Comment (paodb) [reply src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapMarker.java]: Good catch! Bad that I missed that. There's no need to have those variables and the initialize method anymore. I just updated the branch.

**Review by javier-godoy — APPROVED** [review]
LGTM
